export const RADICAL_DICT: Record<string, { pinyin: string, vi: string, meaning: string }> = {
  "一": { pinyin: "yī", vi: "nhất", meaning: "một" },
  "丨": { pinyin: "gǔn", vi: "cổn", meaning: "nét sổ" },
  "丶": { pinyin: "zhǔ", vi: "chủ", meaning: "nét chấm" },
  "丿": { pinyin: "piě", vi: "phiệt", meaning: "nét phẩy" },
  "乙": { pinyin: "yǐ", vi: "ất", meaning: "vị trí thứ hai can chi" },
  "亅": { pinyin: "jué", vi: "quyết", meaning: "nét sổ có móc" },
  "二": { pinyin: "èr", vi: "nhị", meaning: "hai" },
  "亠": { pinyin: "tóu", vi: "đầu", meaning: "phần đầu" },
  "人": { pinyin: "rén", vi: "nhân", meaning: "người (亻)" },
  "亻": { pinyin: "rén", vi: "nhân", meaning: "người" },
  "儿": { pinyin: "ér", vi: "nhi", meaning: "trẻ con" },
  "入": { pinyin: "rù", vi: "nhập", meaning: "vào" },
  "八": { pinyin: "bā", vi: "bát", meaning: "tám" },
  "冂": { pinyin: "jiōng", vi: "quynh", meaning: "vùng biên giới xa" },
  "冖": { pinyin: "mì", vi: "mịch", meaning: "trùm khăn lên" },
  "冫": { pinyin: "bīng", vi: "băng", meaning: "nước đá" },
  "几": { pinyin: "jī", vi: "kỷ", meaning: "ghế dựa" },
  "凵": { pinyin: "kǎn", vi: "khảm", meaning: "há miệng" },
  "刀": { pinyin: "dāo", vi: "đao", meaning: "con dao (刂)" },
  "刂": { pinyin: "dāo", vi: "đao", meaning: "con dao" },
  "力": { pinyin: "lì", vi: "lực", meaning: "sức mạnh" },
  "勹": { pinyin: "bāo", vi: "bao", meaning: "bao bọc" },
  "匕": { pinyin: "bǐ", vi: "chủy", meaning: "cái thìa" },
  "匚": { pinyin: "fāng", vi: "phương", meaning: "tủ đựng" },
  "匸": { pinyin: "xǐ", vi: "hệ", meaning: "che đậy" },
  "十": { pinyin: "shí", vi: "thập", meaning: "mười" },
  "卜": { pinyin: "bǔ", vi: "bốc", meaning: "xem bói" },
  "卩": { pinyin: "jié", vi: "tiết", meaning: "đốt tre" },
  "厂": { pinyin: "hǎn", vi: "hán", meaning: "sườn núi" },
  "厶": { pinyin: "sī", vi: "khư", meaning: "riêng tư" },
  "又": { pinyin: "yòu", vi: "hựu", meaning: "lại, tay phải" },
  "口": { pinyin: "kǒu", vi: "khẩu", meaning: "cái miệng" },
  "囗": { pinyin: "wéi", vi: "vi", meaning: "bao quanh" },
  "土": { pinyin: "tǔ", vi: "thổ", meaning: "đất" },
  "士": { pinyin: "shì", vi: "sĩ", meaning: "kẻ sĩ" },
  "夂": { pinyin: "zhǐ", vi: "truy", meaning: "đi theo sau" },
  "夊": { pinyin: "suī", vi: "truy", meaning: "đi chậm" },
  "夕": { pinyin: "xī", vi: "tịch", meaning: "buổi tối" },
  "大": { pinyin: "dà", vi: "đại", meaning: "to lớn" },
  "女": { pinyin: "nǚ", vi: "nữ", meaning: "phụ nữ" },
  "子": { pinyin: "zǐ", vi: "tử", meaning: "con cái" },
  "宀": { pinyin: "mián", vi: "miên", meaning: "mái nhà" },
  "寸": { pinyin: "cùn", vi: "thốn", meaning: "đơn vị đo (tấc)" },
  "小": { pinyin: "xiǎo", vi: "tiểu", meaning: "nhỏ bé" },
  "尢": { pinyin: "wāng", vi: "uông", meaning: "yếu đuối" },
  "尸": { pinyin: "shī", vi: "thi", meaning: "thây ma" },
  "屮": { pinyin: "chè", vi: "triệt", meaning: "cỏ non" },
  "山": { pinyin: "shān", vi: "sơn", meaning: "núi" },
  "巛": { pinyin: "chuān", vi: "xuyên", meaning: "sông ngòi" },
  "工": { pinyin: "gōng", vi: "công", meaning: "người thợ" },
  "己": { pinyin: "jǐ", vi: "kỷ", meaning: "bản thân" },
  "巾": { pinyin: "jīn", vi: "cân", meaning: "cái khăn" },
  "干": { pinyin: "gān", vi: "can", meaning: "can dự" },
  "幺": { pinyin: "yāo", vi: "yêu", meaning: "nhỏ bé" },
  "广": { pinyin: "yǎn", vi: "nghiễm", meaning: "mái nhà" },
  "廴": { pinyin: "yǐn", vi: "dẫn", meaning: "bước đi" },
  "廾": { pinyin: "gǒng", vi: "củng", meaning: "chắp tay" },
  "弋": { pinyin: "yì", vi: "dặc", meaning: "cọc buộc" },
  "弓": { pinyin: "gōng", vi: "cung", meaning: "cây cung" },
  "彐": { pinyin: "jì", vi: "ký", meaning: "đầu con nhím" },
  "彡": { pinyin: "shān", vi: "sam", meaning: "lông mao" },
  "彳": { pinyin: "chì", vi: "xích", meaning: "bước đi chậm" },
  "心": { pinyin: "xīn", vi: "tâm", meaning: "trái tim (忄)" },
  "忄": { pinyin: "xīn", vi: "tâm", meaning: "trái tim" },
  "戈": { pinyin: "gē", vi: "qua", meaning: "cây qua (vũ khí)" },
  "戶": { pinyin: "hù", vi: "hộ", meaning: "cửa một cánh" },
  "手": { pinyin: "shǒu", vi: "thủ", meaning: "cái tay (扌)" },
  "扌": { pinyin: "shǒu", vi: "thủ", meaning: "cái tay" },
  "支": { pinyin: "zhī", vi: "chi", meaning: "cành cây" },
  "攴": { pinyin: "pū", vi: "phộc", meaning: "đánh nhẹ (攵)" },
  "攵": { pinyin: "pū", vi: "phộc", meaning: "đánh nhẹ" },
  "文": { pinyin: "wén", vi: "văn", meaning: "văn vẻ" },
  "斗": { pinyin: "dǒu", vi: "đẩu", meaning: "cái đấu" },
  "斤": { pinyin: "jīn", vi: "cân", meaning: "cái búa" },
  "方": { pinyin: "fāng", vi: "phương", meaning: "vuông" },
  "无": { pinyin: "wú", vi: "vô", meaning: "không có" },
  "日": { pinyin: "rì", vi: "nhật", meaning: "mặt trời" },
  "曰": { pinyin: "yuē", vi: "viết", meaning: "nói rằng" },
  "月": { pinyin: "yuè", vi: "nguyệt", meaning: "mặt trăng" },
  "木": { pinyin: "mù", vi: "mộc", meaning: "cây" },
  "欠": { pinyin: "qiàn", vi: "khiếm", meaning: "thiếu" },
  "止": { pinyin: "zhǐ", vi: "chỉ", meaning: "dừng lại" },
  "歹": { pinyin: "dǎi", vi: "đãi", meaning: "xấu xa" },
  "殳": { pinyin: "shū", vi: "thù", meaning: "binh khí" },
  "毋": { pinyin: "wú", vi: "vô", meaning: "chớ, đừng" },
  "比": { pinyin: "bǐ", vi: "tỷ", meaning: "so sánh" },
  "毛": { pinyin: "máo", vi: "mao", meaning: "lông" },
  "氏": { pinyin: "shì", vi: "thị", meaning: "họ" },
  "气": { pinyin: "qì", vi: "khí", meaning: "hơi thở, khí" },
  "水": { pinyin: "shuǐ", vi: "thủy", meaning: "nước (氵)" },
  "氵": { pinyin: "shuǐ", vi: "thủy", meaning: "nước" },
  "火": { pinyin: "huǒ", vi: "hỏa", meaning: "lửa (灬)" },
  "灬": { pinyin: "huǒ", vi: "hỏa", meaning: "lửa" },
  "爪": { pinyin: "zhǎo", vi: "trảo", meaning: "móng vuốt" },
  "父": { pinyin: "fù", vi: "phụ", meaning: "cha" },
  "爻": { pinyin: "yáo", vi: "hào", meaning: "hào (kinh dịch)" },
  "爿": { pinyin: "qiáng", vi: "tường", meaning: "mảnh gỗ" },
  "片": { pinyin: "piàn", vi: "phiến", meaning: "tấm, mảnh" },
  "牙": { pinyin: "yá", vi: "nha", meaning: "răng" },
  "牛": { pinyin: "niú", vi: "ngưu", meaning: "con trâu" },
  "犬": { pinyin: "quǎn", vi: "khuyển", meaning: "con chó (犭)" },
  "犭": { pinyin: "quǎn", vi: "khuyển", meaning: "con chó" },
  "玄": { pinyin: "xuán", vi: "huyền", meaning: "màu đen" },
  "玉": { pinyin: "yù", vi: "ngọc", meaning: "đá quý" },
  "瓜": { pinyin: "guā", vi: "qua", meaning: "quả dưa" },
  "瓦": { pinyin: "wǎ", vi: "ngõa", meaning: "ngói" },
  "甘": { pinyin: "gān", vi: "cam", meaning: "ngọt" },
  "生": { pinyin: "shēng", vi: "sinh", meaning: "sinh đẻ" },
  "用": { pinyin: "yòng", vi: "dụng", meaning: "sử dụng" },
  "田": { pinyin: "tián", vi: "điền", meaning: "ruộng" },
  "疋": { pinyin: "pǐ", vi: "thất", meaning: "đơn vị đo" },
  "疒": { pinyin: "chuáng", vi: "nạch", meaning: "bệnh tật" },
  "癶": { pinyin: "bō", vi: "bát", meaning: "bước đi" },
  "白": { pinyin: "bái", vi: "bạch", meaning: "màu trắng" },
  "皮": { pinyin: "pí", vi: "bì", meaning: "da" },
  "皿": { pinyin: "mǐn", vi: "mãnh", meaning: "bát đĩa" },
  "目": { pinyin: "mù", vi: "mục", meaning: "mắt" },
  "矛": { pinyin: "máo", vi: "mâu", meaning: "cây giáo" },
  "矢": { pinyin: "shǐ", vi: "thỉ", meaning: "mũi tên" },
  "石": { pinyin: "shí", vi: "thạch", meaning: "đá" },
  "示": { pinyin: "shì", vi: "thị", meaning: "chỉ thị (礻)" },
  "礻": { pinyin: "shì", vi: "thị", meaning: "chỉ thị" },
  "禸": { pinyin: "róu", vi: "nhựu", meaning: "dấu chân thú" },
  "禾": { pinyin: "hé", vi: "hòa", meaning: "lúa" },
  "穴": { pinyin: "xué", vi: "huyệt", meaning: "hang lỗ" },
  "立": { pinyin: "lì", vi: "lập", meaning: "đứng" },
  "竹": { pinyin: "zhú", vi: "trúc", meaning: "cây trúc" },
  "米": { pinyin: "mǐ", vi: "mễ", meaning: "gạo" },
  "糸": { pinyin: "mì", vi: "mịch", meaning: "sợi tơ (纟)" },
  "缶": { pinyin: "fǒu", vi: "phẫu", meaning: "đồ sành" },
  "网": { pinyin: "wǎng", vi: "võng", meaning: "cái lưới" },
  "羊": { pinyin: "yáng", vi: "dương", meaning: "con dê" },
  "羽": { pinyin: "yǔ", vi: "vũ", meaning: "lông vũ" },
  "老": { pinyin: "lǎo", vi: "lão", meaning: "già" },
  "而": { pinyin: "ér", vi: "nhi", meaning: "mà, và" },
  "耒": { pinyin: "lěi", vi: "lỗi", meaning: "cái cày" },
  "耳": { pinyin: "ěr", vi: "nhĩ", meaning: "tai" },
  "聿": { pinyin: "yù", vi: "duật", meaning: "cây bút" },
  "肉": { pinyin: "ròu", vi: "nhục", meaning: "thịt" },
  "臣": { pinyin: "chén", vi: "thần", meaning: "quan thần" },
  "自": { pinyin: "zì", vi: "tự", meaning: "tự bản thân" },
  "至": { pinyin: "zhì", vi: "chí", meaning: "đến nơi" },
  "臼": { pinyin: "jiù", vi: "cữu", meaning: "cái cối" },
  "舌": { pinyin: "shé", vi: "thiệt", meaning: "cái lưỡi" },
  "舛": { pinyin: "chuǎn", vi: "suyễn", meaning: "sai trái" },
  "舟": { pinyin: "zhōu", vi: "chu", meaning: "cái thuyền" },
  "艮": { pinyin: "gěn", vi: "cấn", meaning: "ngừng lại" },
  "色": { pinyin: "sè", vi: "sắc", meaning: "màu sắc" },
  "艸": { pinyin: "cǎo", vi: "thảo", meaning: "cỏ (艹)" },
  "艹": { pinyin: "cǎo", vi: "thảo", meaning: "cỏ" },
  "虍": { pinyin: "hū", vi: "hô", meaning: "vằn hổ" },
  "虫": { pinyin: "chóng", vi: "trùng", meaning: "côn trùng" },
  "血": { pinyin: "xuè", vi: "huyết", meaning: "máu" },
  "行": { pinyin: "xíng", vi: "hành", meaning: "đi" },
  "衣": { pinyin: "yī", vi: "y", meaning: "quần áo (衤)" },
  "衤": { pinyin: "yī", vi: "y", meaning: "quần áo" },
  "襾": { pinyin: "yà", vi: "á", meaning: "che đậy" },
  "見": { pinyin: "jiàn", vi: "kiến", meaning: "nhìn thấy" },
  "角": { pinyin: "jiǎo", vi: "giác", meaning: "cái sừng" },
  "言": { pinyin: "yán", vi: "ngôn", meaning: "lời nói (訁)" },
  "訁": { pinyin: "yán", vi: "ngôn", meaning: "lời nói" },
  "谷": { pinyin: "gǔ", vi: "cốc", meaning: "thung lũng" },
  "豆": { pinyin: "dòu", vi: "đậu", meaning: "hạt đậu" },
  "豕": { pinyin: "shǐ", vi: "thỉ", meaning: "con lợn" },
  "豸": { pinyin: "zhì", vi: "trãi", meaning: "loài không chân" },
  "貝": { pinyin: "bèi", vi: "bối", meaning: "vỏ sò" },
  "赤": { pinyin: "chì", vi: "xích", meaning: "màu đỏ" },
  "走": { pinyin: "zǒu", vi: "tẩu", meaning: "chạy" },
  "足": { pinyin: "zú", vi: "túc", meaning: "cái chân" },
  "身": { pinyin: "shēn", vi: "thân", meaning: "thân thể" },
  "車": { pinyin: "chē", vi: "xa", meaning: "xe cộ" },
  "辛": { pinyin: "xīn", vi: "tân", meaning: "cay đắng" },
  "辰": { pinyin: "chén", vi: "thần", meaning: "thì giờ" },
  "辵": { pinyin: "chuò", vi: "sước", meaning: "bước đi (辶)" },
  "辶": { pinyin: "chuò", vi: "sước", meaning: "bước đi" },
  "邑": { pinyin: "yì", vi: "ấp", meaning: "vùng đất (阝 phải)" },
  "酉": { pinyin: "yǒu", vi: "dậu", meaning: "chi dậu" },
  "釆": { pinyin: "biàn", vi: "biện", meaning: "phân biệt" },
  "里": { pinyin: "lǐ", vi: "lý", meaning: "dặm" },
  "金": { pinyin: "jīn", vi: "kim", meaning: "kim loại (釒)" },
  "釒": { pinyin: "jīn", vi: "kim", meaning: "kim loại" },
  "長": { pinyin: "cháng", vi: "trường", meaning: "dài" },
  "門": { pinyin: "mén", vi: "môn", meaning: "cửa" },
  "阜": { pinyin: "fù", vi: "phụ", meaning: "gò đất (阝 trái)" },
  "阝": { pinyin: "fù", vi: "phụ / ấp", meaning: "gò đất / vùng đất" },
  "隶": { pinyin: "lì", vi: "đãi", meaning: "kịp đến" },
  "隹": { pinyin: "zhuī", vi: "chuy", meaning: "chim đuôi ngắn" },
  "雨": { pinyin: "yǔ", vi: "vũ", meaning: "mưa" },
  "青": { pinyin: "qīng", vi: "thanh", meaning: "màu xanh" },
  "非": { pinyin: "fēi", vi: "phi", meaning: "không đúng" },
  "面": { pinyin: "miàn", vi: "diện", meaning: "khuôn mặt" },
  "革": { pinyin: "gé", vi: "cách", meaning: "da thú" },
  "韋": { pinyin: "wéi", vi: "vi", meaning: "da mềm" },
  "韭": { pinyin: "jiǔ", vi: "cửu", meaning: "rau hẹ" },
  "音": { pinyin: "yīn", vi: "âm", meaning: "âm thanh" },
  "頁": { pinyin: "yè", vi: "hiệt", meaning: "trang giấy" },
  "風": { pinyin: "fēng", vi: "phong", meaning: "gió" },
  "飛": { pinyin: "fēi", vi: "phi", meaning: "bay" },
  "食": { pinyin: "shí", vi: "thực", meaning: "ăn (飠)" },
  "飠": { pinyin: "shí", vi: "thực", meaning: "ăn" },
  "首": { pinyin: "shǒu", vi: "thủ", meaning: "cái đầu" },
  "香": { pinyin: "xiāng", vi: "hương", meaning: "thơm" },
  "馬": { pinyin: "mǎ", vi: "mã", meaning: "con ngựa" },
  "骨": { pinyin: "gǔ", vi: "cốt", meaning: "xương" },
  "高": { pinyin: "gāo", vi: "cao", meaning: "cao" },
  "髟": { pinyin: "biāo", vi: "bưu", meaning: "tóc dài" },
  "鬥": { pinyin: "dòu", vi: "đấu", meaning: "đánh nhau" },
  "鬯": { pinyin: "chàng", vi: "xưởng", meaning: "rượu nếp" },
  "鬲": { pinyin: "lì", vi: "cách", meaning: "cái đỉnh" },
  "鬼": { pinyin: "guǐ", vi: "quỷ", meaning: "ma quỷ" },
  "魚": { pinyin: "yú", vi: "ngư", meaning: "con cá" },
  "鳥": { pinyin: "niǎo", vi: "điểu", meaning: "con chim" },
  "鹵": { pinyin: "lǔ", vi: "lỗ", meaning: "đất mặn" },
  "鹿": { pinyin: "lù", vi: "lộc", meaning: "hươu" },
  "麥": { pinyin: "mài", vi: "mạch", meaning: "lúa mạch" },
  "麻": { pinyin: "má", vi: "ma", meaning: "cây gai" },
  "黃": { pinyin: "huáng", vi: "hoàng", meaning: "màu vàng" },
  "黍": { pinyin: "shǔ", vi: "thử", meaning: "lúa nếp" },
  "黑": { pinyin: "hēi", vi: "hắc", meaning: "màu đen" },
  "黹": { pinyin: "zhǐ", vi: "chỉ", meaning: "may vá" },
  "黽": { pinyin: "mǐn", vi: "mãnh", meaning: "con ếch" },
  "鼎": { pinyin: "dǐng", vi: "đỉnh", meaning: "cái đỉnh" },
  "鼓": { pinyin: "gǔ", vi: "cổ", meaning: "cái trống" },
  "鼠": { pinyin: "shǔ", vi: "thử", meaning: "con chuột" },
  "鼻": { pinyin: "bí", vi: "tị", meaning: "cái mũi" },
  "齊": { pinyin: "qí", vi: "tề", meaning: "bằng phẳng" },
  "齒": { pinyin: "chǐ", vi: "xỉ", meaning: "răng" },
  "龍": { pinyin: "lóng", vi: "long", meaning: "con rồng" },
  "龜": { pinyin: "guī", vi: "quy", meaning: "con rùa" },
  "龠": { pinyin: "yuè", vi: "dược", meaning: "ống sáo" }
};
